import React from "react";
import type { NextPage } from "next";
import SigninForm from "../../Components/Page/Authentication/signin";
import Head from "next/head";
const Signin: NextPage = () => {
  return (
    <>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SigninForm/>
      </main>
    </>
  );
};

export default Signin;
