import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import TabComponent from '../../Components/Universal/Tab/tab';
import { Tabs, TabList, Tab, TabPanel, TabPanels } from "@chakra-ui/react";
import Main from '../../Components/Page/Personal/Main/main';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Personal Finances</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{marginTop:"50px",width:"90%", marginInline:"auto",minHeight:"80vh"}}>
      <Main/>
      </main>
    </div>
  )
}

export default Home
