import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Landing from "../Components/Page/Home/Landing/landing";
import Services from "../Components/Page/Home/Services/services";
import Pricing from '../Components/Page/Home/Pricing/pricing';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Landing/>
        <Services/>
        <Pricing/>
      </div>
    </div>
  )
}

export default Home
