import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Landing from "../Components/Page/Home/Landing/landing";
import Services from "../Components/Page/Home/Services/services";
import Pricing from '../Components/Page/Home/Pricing/pricing';
import { useSelector} from "react-redux";
import {RootState} from "../app/store";
const Home: NextPage = () => {
  const isSignedin=useSelector((state:RootState) =>{
    return state.user.isSignedin;
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Landing isSignedin={isSignedin}/>
        <Services isSignedin={isSignedin}/>
        <Pricing isSignedin={isSignedin}/>
      </div>
    </div>
  )
}

export default Home
